### ISSUE TITLE
What is the current version number?

### ISSUE THREAD

**Issue by Isabellle** [rockerhieu/rv-adapter-states#3]
Sorry for asking that, but could help me finding the current version number to add the right one in the gradle file?
Thanks a lot!

**Comment by rockerhieu** [comment]
`1.0` is the one to go. See https://github.com/rockerhieu/rv-adapter-states/blob/master/README.md.

**Comment by Isabellle** [comment]
Thanks. I was on it, where is the version displayed? (for future)

**Comment by rockerhieu** [comment]
Don't you see it in the README file?

<img width="256" alt="screen shot 2016-05-16 at 12 14 49 pm" src="https://cloud.githubusercontent.com/assets/1281889/15280877/d5677374-1b5f-11e6-9942-fa1373b2867a.png">
